services:
  app:
    build: .
    command: sh -c "npm run migrate && node dist/main.js"
    container_name: typescript-app 
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  db:  
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12346
      POSTGRES_DB: docker
    ports:
      - "5433:5432"  
