export const ERROR_MESSAGES = {
  MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
  PRODCUT_EXISTS: "PRODUCT_EXISTS",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  INVALID_CREDENTIALS: "Invalid credentials",
  PRODUCT_CREATION_FAILED: "PRODUCT_CREATION_FAILED",
  INTERNAL_SERVER_ERROR: "Internal Server Error.",
  REDIS_SERVER_ERROR: "Couldn't reach Redis.",
};

